apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.namespace}}
  name: cyberdock.ecs
  labels:
    {{- include "cyberdock.labels" . | nindent 4 }}
    cyberdock: ecs
spec:
  selector:
    app: cyberdock.ecs
    {{- include "cyberdock.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 32262
      targetPort: 9200
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{.Values.namespace}}
  name: cyberdock.es-config
  labels:
    {{- include "cyberdock.labels" . | nindent 4 }}
data:
  elasticsearch.yml: |
    cluster.name: esnode-0
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    discovery.zen.ping.unicast.hosts: elasticsearch-cluster
    discovery.zen.minimum_master_nodes: 1
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{.Values.namespace}}
  name: cyberdock.esnode
  labels:
    cyberdock: ecs-node
    {{- include "cyberdock.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      cyberdock: ecs-node
      {{- include "cyberdock.selectorLabels" . | nindent 6 }}
  serviceName: elasticsearch
  replicas: {{ .Values.elasticReplicaCount }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cyberdock.ecs
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-sysctl
          image: busybox
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
      containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 512m
          securityContext:
            privileged: true
            runAsUser: 1000
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
          image: docker.elastic.co/elasticsearch/elasticsearch:6.8.0
          env:
            - name: ES_JAVA_OPTS
              value: -Xms128m -Xmx128m
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /_cluster/health?local=true
              port: 9200
            initialDelaySeconds: 5
          ports:
            - containerPort: 9200
              name: es-http
            - containerPort: 9300
              name: es-transport
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
      volumes:
        - name: elasticsearch-config
          configMap:
            name: es-config
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
  volumeClaimTemplates:
    - metadata:
        name: es-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
